// The apartments list. Edit this file to add apartments or rule them out.
//
//   enabled: true   -> shown in the app
//   enabled: false  -> ruled out (hidden unless "Show ruled out" is ticked)
//
// Files for each apartment live in apartments/<id>/.
// planFile: the traced plan (walls, doors, windows) used for the 2D/3D view.
// calibration: for apartments without a traced plan, two points on the floor
// plan image (in image pixels) and the real distance between them in cm. Set it
// from the app with "Set scale", then Export so it is saved for everyone.
// layout: saved furniture (also exported from the app).
// allIn: rent plus any fees not included, per month (used to rank in Compare).

window.CURRENCY = "HK$";

window.APARTMENTS = [
  {
    id: "ming-sun-building",
    enabled: true,
    name: "Ming Sun Building",
    building: "Ming Sun Building",
    address: "90-96 Tung Lo Wan Road, Tai Hang / Tin Hau",
    url: "https://www.28hse.com/en/rent/apartment/property-4015019",
    rent: 22000,
    fees: "Management HK$1,875/mo; rates not included",
    allIn: 23875,
    beds: 1,
    baths: 1,
    sqft: 466,
    floor: "",
    available: "",
    commute: "",
    pros: "Fully rebuilt building, premium renovation; separate kitchen; furnished with appliances incl. washer; pet friendly; walk to Tin Hau MTR",
    cons: "Rates on top of rent",
    notes: "Listed by Omura Property (28hse #4015019). Long-term lease preferred.",
    photos: [
      "apartments/ming-sun-building/photo-01.jpg",
      "apartments/ming-sun-building/photo-02.jpg",
      "apartments/ming-sun-building/photo-03.jpg",
      "apartments/ming-sun-building/photo-04.jpg",
      "apartments/ming-sun-building/photo-05.jpg",
      "apartments/ming-sun-building/photo-06.jpg",
      "apartments/ming-sun-building/photo-07.jpg",
      "apartments/ming-sun-building/photo-08.jpg",
      "apartments/ming-sun-building/photo-09.jpg",
      "apartments/ming-sun-building/photo-10.jpg",
      "apartments/ming-sun-building/photo-11.jpg",
      "apartments/ming-sun-building/photo-12.jpg",
      "apartments/ming-sun-building/photo-13.jpg",
      "apartments/ming-sun-building/photo-14.jpg",
      "apartments/ming-sun-building/photo-15.jpg",
      "apartments/ming-sun-building/photo-16.jpg",
      "apartments/ming-sun-building/photo-17.jpg",
      "apartments/ming-sun-building/photo-18.jpg",
      "apartments/ming-sun-building/photo-19.jpg",
      "apartments/ming-sun-building/photo-20.jpg",
      "apartments/ming-sun-building/photo-21.jpg",
      "apartments/ming-sun-building/photo-22.jpg",
      "apartments/ming-sun-building/photo-23.jpg"
    ],
    floorPlan: "apartments/ming-sun-building/floorplan.jpg",
    planFile: "apartments/ming-sun-building/plan.js",
    layout: []
  },
  {
    id: "ying-wa-court",
    enabled: true,
    name: "Ying Wa Court",
    building: "Ying Wa Court",
    address: "12 Ying Wa Terrace, Mid-Levels West",
    url: "https://www.28hse.com/en/rent/apartment/property-4036766",
    rent: 25000,
    fees: "Management fee not stated",
    beds: 2,
    baths: 1,
    sqft: 466,
    grossSqft: 728,
    floor: "",
    available: "Ready now (key with agent)",
    commute: "",
    pros: "Newly renovated; close to MTR",
    cons: "",
    notes: "Richfield Property (28hse #4036766). No floor plan on the listing.",
    photos: [
      "apartments/ying-wa-court/photo-01.jpg",
      "apartments/ying-wa-court/photo-02.jpg",
      "apartments/ying-wa-court/photo-03.jpg",
      "apartments/ying-wa-court/photo-04.jpg",
      "apartments/ying-wa-court/photo-05.jpg",
      "apartments/ying-wa-court/photo-06.jpg",
      "apartments/ying-wa-court/photo-07.jpg"
    ],
    floorPlan: "",
    layout: []
  },
  {
    id: "beaudry-tower",
    enabled: true,
    name: "Beaudry Tower",
    building: "Beaudry Tower (1989, 32 floors)",
    address: "38 Bonham Road, Mid-Levels West",
    url: "https://www.28hse.com/en/rent/apartment/property-4042863",
    rent: 25000,
    fees: "Management fee and rates included",
    allIn: 25000,
    beds: 1,
    baths: 1,
    sqft: 498,
    grossSqft: 686,
    floor: "Middle",
    available: "",
    commute: "",
    pros: "Large bedroom with built-in wardrobe; open view; ~5 min walk to MTR",
    cons: "Older building (1989)",
    notes: "At Home Property (28hse #4042863). Plan is Flat A from the developer's brochure, the only 498 sq ft unit in the building.",
    photos: [
      "apartments/beaudry-tower/photo-01.jpg",
      "apartments/beaudry-tower/photo-02.jpg",
      "apartments/beaudry-tower/photo-03.jpg",
      "apartments/beaudry-tower/photo-04.jpg",
      "apartments/beaudry-tower/photo-05.jpg",
      "apartments/beaudry-tower/photo-06.jpg",
      "apartments/beaudry-tower/photo-07.jpg",
      "apartments/beaudry-tower/photo-08.jpg",
      "apartments/beaudry-tower/photo-09.jpg",
      "apartments/beaudry-tower/photo-10.jpg"
    ],
    floorPlan: "apartments/beaudry-tower/floorplan.jpg",
    planFile: "apartments/beaudry-tower/plan.js",
    layout: []
  },
  {
    id: "honor-villa",
    enabled: true,
    name: "Honor Villa",
    building: "Honor Villa (~26 yrs old)",
    address: "75 Caine Road, Mid-Levels West",
    url: "https://www.28hse.com/en/rent/apartment/property-4013550",
    rent: 28000,
    fees: "Management fee and rates included",
    allIn: 28000,
    beds: 2,
    baths: 1,
    sqft: 446,
    grossSqft: 685,
    floor: "Middle",
    available: "",
    commute: "",
    pros: "Large wardrobe; convenient location",
    cons: "~13 min walk to MTR; smallest of the four",
    notes: "28hse #4013550. Plan is Flat A from the developer's brochure, the only 446 sq ft unit in the building.",
    photos: [
      "apartments/honor-villa/photo-01.jpg",
      "apartments/honor-villa/photo-02.jpg",
      "apartments/honor-villa/photo-03.jpg",
      "apartments/honor-villa/photo-04.jpg",
      "apartments/honor-villa/photo-05.jpg",
      "apartments/honor-villa/photo-06.jpg"
    ],
    floorPlan: "apartments/honor-villa/floorplan.jpg",
    planFile: "apartments/honor-villa/plan.js",
    layout: []
  },
  {
    id: "example",
    enabled: false,
    name: "Example 1BR (demo)",
    address: "Not a real listing",
    url: "",
    rent: 2500,
    fees: "",
    beds: 1,
    baths: 1,
    sqft: 720,
    available: "",
    commute: "",
    pros: "Big living room",
    cons: "Small bath",
    notes: "Demo apartment so you can try the tools. Set enabled: false to hide it.",
    photos: [],
    floorPlan: "apartments/example/floorplan.svg",
    calibration: { x1: 60, y1: 30, x2: 660, y2: 30, inches: 360 },
    layout: []
  }
];
