// Honor Villa, Flat A (2 bedrooms, 446 sq ft saleable).
// Generated by tools/trace_plans.py from floorplan.jpg. Units are cm.
window.PLANS = window.PLANS || {};
window.PLANS["honor-villa"] = {
 "source": "Traced from the developer's plan for Flat A (5/F to 29/F, 446 sq ft saleable) using its printed dimensions. The listing doesn't say which flat; A is the only 446 sq ft unit. The front door position is inferred.",
 "ceiling": 265,
 "defaultPreset": "two",
 "presetNames": {
  "two": "Double bed + guest/study",
  "office": "Double bed + home office",
  "empty": "Empty flat"
 },
 "presets": {
  "two": [
   [
    "bed-double",
    136,
    448,
    135,
    190,
    270
   ],
   [
    "nightstand",
    55,
    326,
    35,
    40,
    270
   ],
   [
    "sofa3",
    521,
    429,
    210,
    90,
    270
   ],
   [
    "coffee",
    630,
    429,
    100,
    55,
    90
   ],
   [
    "tv",
    752,
    429,
    160,
    40,
    90
   ],
   [
    "dining4",
    588,
    143,
    120,
    75
   ],
   [
    "chair",
    557,
    88,
    45,
    50
   ],
   [
    "chair",
    618,
    88,
    45,
    50
   ],
   [
    "chair",
    557,
    198,
    45,
    50,
    180
   ],
   [
    "chair",
    618,
    198,
    45,
    50,
    180
   ],
   [
    "shoe",
    716,
    76,
    80,
    30,
    270
   ],
   [
    "bed-single",
    417,
    448,
    90,
    190,
    180
   ],
   [
    "dresser",
    313,
    533,
    80,
    40,
    180
   ]
  ],
  "office": [
   [
    "bed-double",
    136,
    448,
    135,
    190,
    270
   ],
   [
    "nightstand",
    55,
    326,
    35,
    40,
    270
   ],
   [
    "sofa3",
    521,
    429,
    210,
    90,
    270
   ],
   [
    "coffee",
    630,
    429,
    100,
    55,
    90
   ],
   [
    "tv",
    752,
    429,
    160,
    40,
    90
   ],
   [
    "dining4",
    588,
    143,
    120,
    75
   ],
   [
    "chair",
    557,
    88,
    45,
    50
   ],
   [
    "chair",
    618,
    88,
    45,
    50
   ],
   [
    "chair",
    557,
    198,
    45,
    50,
    180
   ],
   [
    "chair",
    618,
    198,
    45,
    50,
    180
   ],
   [
    "shoe",
    716,
    76,
    80,
    30,
    270
   ],
   [
    "desk",
    359,
    521,
    120,
    60,
    180
   ],
   [
    "officechair",
    359,
    460,
    60,
    60
   ],
   [
    "bookshelf",
    450,
    405,
    80,
    30,
    270
   ]
  ],
  "empty": []
 },
 "rooms": [
  {
   "n": "Bedroom 1",
   "x": 143,
   "y": 466,
   "dim": "2.3 × 2.6 m"
  },
  {
   "n": "Bedroom 2",
   "x": 359,
   "y": 466,
   "dim": "2.0 × 2.6 m"
  },
  {
   "n": "Living",
   "x": 624,
   "y": 466,
   "dim": "3.1 × 2.6 m"
  },
  {
   "n": "Dining",
   "x": 582,
   "y": 137,
   "dim": "2.9 × 2.9 m"
  },
  {
   "n": "Kitchen",
   "x": 338,
   "y": 137
  },
  {
   "n": "Bath",
   "x": 112,
   "y": 259
  }
 ],
 "notes": [
  {
   "x": 679,
   "y": -14,
   "text": "front door (approx.)"
  },
  {
   "x": 399,
   "y": 632,
   "text": "facing Caine Road"
  }
 ],
 "reference": {
  "x": -296.3,
  "y": -107.3,
  "w": 1269.5,
  "h": 1164.6
 },
 "bounds": [
  -10,
  -10,
  801,
  624
 ],
 "floors": [
  {
   "r": [
    35,
    15,
    156,
    284
   ],
   "kind": "bath"
  },
  {
   "r": [
    191,
    15,
    241,
    189
   ],
   "kind": "kitchen"
  },
  {
   "r": [
    191,
    204,
    537,
    95
   ],
   "kind": "wood"
  },
  {
   "r": [
    433,
    15,
    295,
    284
   ],
   "kind": "wood"
  },
  {
   "r": [
    35,
    299,
    748,
    262
   ],
   "kind": "wood"
  }
 ],
 "walls": [
  {
   "a": [
    18,
    7
   ],
   "b": [
    746,
    7
   ],
   "t": 14,
   "o": [
    {
     "k": "door",
     "side": 1,
     "h": "e",
     "s": 624,
     "e": 698
    }
   ]
  },
  {
   "a": [
    18,
    7
   ],
   "b": [
    18,
    561
   ],
   "t": 24
  },
  {
   "a": [
    746,
    7
   ],
   "b": [
    746,
    332
   ],
   "t": 26
  },
  {
   "a": [
    746,
    332
   ],
   "b": [
    779,
    332
   ],
   "t": 12
  },
  {
   "a": [
    779,
    332
   ],
   "b": [
    779,
    561
   ],
   "t": 14,
   "o": [
    {
     "k": "win",
     "s": 67,
     "e": 226
    }
   ]
  },
  {
   "a": [
    18,
    561
   ],
   "b": [
    779,
    561
   ],
   "t": 12,
   "o": [
    {
     "k": "win",
     "s": 70,
     "e": 228
    },
    {
     "k": "win",
     "s": 283,
     "e": 441
    },
    {
     "k": "win",
     "s": 493,
     "e": 759
    }
   ]
  },
  {
   "a": [
    191,
    7
   ],
   "b": [
    191,
    299
   ],
   "t": 10,
   "o": [
    {
     "k": "door",
     "side": -1,
     "h": "e",
     "s": 212,
     "e": 283
    }
   ]
  },
  {
   "a": [
    191,
    204
   ],
   "b": [
    433,
    204
   ],
   "t": 10
  },
  {
   "a": [
    433,
    7
   ],
   "b": [
    433,
    70
   ],
   "t": 10
  },
  {
   "a": [
    18,
    299
   ],
   "b": [
    250,
    299
   ],
   "t": 10,
   "o": [
    {
     "k": "door",
     "side": 1,
     "h": "e",
     "s": 139,
     "e": 222
    }
   ]
  },
  {
   "a": [
    250,
    299
   ],
   "b": [
    250,
    561
   ],
   "t": 10
  },
  {
   "a": [
    250,
    299
   ],
   "b": [
    466,
    299
   ],
   "t": 10,
   "o": [
    {
     "k": "door",
     "side": 1,
     "h": "s",
     "s": 5,
     "e": 88
    }
   ]
  },
  {
   "a": [
    466,
    299
   ],
   "b": [
    466,
    561
   ],
   "t": 10
  }
 ],
 "fixtures": [
  {
   "h": 55,
   "color": "#f4f4f2",
   "label": "Bath",
   "round": 1,
   "r": [
    48,
    24,
    134,
    54
   ]
  },
  {
   "h": 40,
   "color": "#f7f7f5",
   "label": "WC",
   "round": 1,
   "r": [
    118,
    112,
    49,
    59
   ]
  },
  {
   "h": 85,
   "label": "Basin",
   "kind": "sink",
   "r": [
    40,
    176,
    44,
    61
   ]
  },
  {
   "h": 90,
   "label": "Hob",
   "kind": "hob",
   "r": [
    199,
    20,
    51,
    178
   ]
  },
  {
   "h": 90,
   "label": "Sink",
   "kind": "sink",
   "r": [
    250,
    20,
    178,
    44
   ]
  },
  {
   "h": 50,
   "color": "#ece6da",
   "label": "bay",
   "r": [
    84,
    561,
    166,
    45
   ]
  },
  {
   "h": 50,
   "color": "#ece6da",
   "label": "bay",
   "r": [
    299,
    561,
    163,
    45
   ]
  },
  {
   "h": 50,
   "color": "#ece6da",
   "label": "bay window",
   "r": [
    509,
    561,
    274,
    45
   ]
  }
 ]
};
