// Beaudry Tower, Flat A (1 bedroom, 498 sq ft saleable).
// Generated by tools/trace_plans.py from floorplan.jpg. Units are cm.
window.PLANS = window.PLANS || {};
window.PLANS["beaudry-tower"] = {
 "source": "Traced from the developer's plan for Flat A (2/F to 29/F, 498 sq ft saleable), scaled to the listed area. The listing doesn't say which flat; A is the only 498 sq ft unit. Sizes are approximate (about ±15 cm).",
 "ceiling": 260,
 "defaultPreset": "study",
 "presetNames": {
  "study": "Lounge + work desk",
  "lounge": "Lounge + dining table",
  "empty": "Empty flat"
 },
 "presets": {
  "lounge": [
   [
    "bed-queen",
    103,
    125,
    152,
    190,
    270
   ],
   [
    "nightstand",
    25,
    22,
    35,
    40,
    270
   ],
   [
    "nightstand",
    25,
    225,
    35,
    40,
    270
   ],
   [
    "wardrobe",
    292,
    28,
    120,
    60
   ],
   [
    "rug",
    399,
    461,
    200,
    140,
    90
   ],
   [
    "sofa3",
    624,
    461,
    210,
    90,
    90
   ],
   [
    "coffee",
    545,
    461,
    100,
    55,
    90
   ],
   [
    "tv",
    168,
    461,
    160,
    40,
    270
   ],
   [
    "shoe",
    632,
    270,
    80,
    30,
    90
   ],
   [
    "dining4",
    320,
    697,
    120,
    75
   ],
   [
    "chair",
    292,
    652,
    45,
    50
   ],
   [
    "chair",
    348,
    652,
    45,
    50
   ],
   [
    "chair",
    292,
    742,
    45,
    50,
    180
   ],
   [
    "chair",
    348,
    742,
    45,
    50,
    180
   ],
   [
    "plant",
    461,
    775,
    40,
    40
   ]
  ],
  "study": [
   [
    "bed-queen",
    103,
    125,
    152,
    190,
    270
   ],
   [
    "nightstand",
    25,
    22,
    35,
    40,
    270
   ],
   [
    "nightstand",
    25,
    225,
    35,
    40,
    270
   ],
   [
    "wardrobe",
    292,
    28,
    120,
    60
   ],
   [
    "rug",
    399,
    461,
    200,
    140,
    90
   ],
   [
    "sofa3",
    624,
    461,
    210,
    90,
    90
   ],
   [
    "coffee",
    545,
    461,
    100,
    55,
    90
   ],
   [
    "tv",
    168,
    461,
    160,
    40,
    270
   ],
   [
    "shoe",
    632,
    270,
    80,
    30,
    90
   ],
   [
    "desk",
    320,
    764,
    120,
    60,
    180
   ],
   [
    "officechair",
    320,
    719,
    60,
    60
   ],
   [
    "round",
    242,
    652,
    90,
    90
   ],
   [
    "bookshelf",
    480,
    680,
    80,
    30,
    90
   ]
  ],
  "empty": []
 },
 "rooms": [
  {
   "n": "Bedroom",
   "x": 191,
   "y": 107,
   "dim": "3.8 × 2.4 m"
  },
  {
   "n": "Bath",
   "x": 466,
   "y": 107
  },
  {
   "n": "Kitchen",
   "x": 264,
   "y": 348
  },
  {
   "n": "Living / dining",
   "x": 399,
   "y": 483,
   "dim": "5.1 × 2.8 m + 3.5 × 2.1 m"
  }
 ],
 "notes": [
  {
   "x": 692,
   "y": 357,
   "text": "front door",
   "rot": 90
  },
  {
   "x": 295,
   "y": 876,
   "text": "facing Bonham Road (sea view)"
  }
 ],
 "reference": {
  "x": -73.1,
  "y": -78.6,
  "w": 807.9,
  "h": 1123.9
 },
 "bounds": [
  -17,
  -23,
  674,
  877
 ],
 "floors": [
  {
   "r": [
    0,
    0,
    376,
    245
   ],
   "kind": "wood"
  },
  {
   "r": [
    146,
    157,
    508,
    433
   ],
   "kind": "wood"
  },
  {
   "r": [
    376,
    157,
    278,
    90
   ],
   "kind": "wood"
  },
  {
   "r": [
    146,
    590,
    348,
    214
   ],
   "kind": "wood"
  },
  {
   "r": [
    376,
    0,
    278,
    157
   ],
   "kind": "bath"
  },
  {
   "r": [
    96,
    245,
    284,
    140
   ],
   "kind": "kitchen"
  }
 ],
 "walls": [
  {
   "a": [
    0,
    0
   ],
   "b": [
    655,
    0
   ],
   "t": 15,
   "o": [
    {
     "k": "win",
     "s": 157,
     "e": 219
    },
    {
     "k": "win",
     "frost": 1,
     "s": 489,
     "e": 551
    }
   ]
  },
  {
   "a": [
    0,
    0
   ],
   "b": [
    0,
    245
   ],
   "t": 20
  },
  {
   "a": [
    0,
    245
   ],
   "b": [
    379,
    245
   ],
   "t": 12,
   "o": [
    {
     "k": "win",
     "s": 20,
     "e": 93
    }
   ]
  },
  {
   "a": [
    376,
    0
   ],
   "b": [
    376,
    157
   ],
   "t": 12
  },
  {
   "a": [
    376,
    157
   ],
   "b": [
    655,
    157
   ],
   "t": 12,
   "o": [
    {
     "k": "door",
     "side": 1,
     "h": "s",
     "s": 70,
     "e": 124
    }
   ]
  },
  {
   "a": [
    96,
    245
   ],
   "b": [
    96,
    385
   ],
   "t": 12,
   "o": [
    {
     "k": "win",
     "s": 14,
     "e": 126
    }
   ]
  },
  {
   "a": [
    96,
    385
   ],
   "b": [
    379,
    385
   ],
   "t": 15
  },
  {
   "a": [
    379,
    245
   ],
   "b": [
    379,
    385
   ],
   "t": 12,
   "o": [
    {
     "k": "open",
     "s": 9,
     "e": 80
    }
   ]
  },
  {
   "a": [
    147,
    385
   ],
   "b": [
    147,
    804
   ],
   "t": 15,
   "o": [
    {
     "k": "win",
     "s": 42,
     "e": 188
    }
   ]
  },
  {
   "a": [
    655,
    0
   ],
   "b": [
    655,
    590
   ],
   "t": 18,
   "o": [
    {
     "k": "door",
     "side": 1,
     "h": "e",
     "s": 314,
     "e": 399
    }
   ]
  },
  {
   "a": [
    494,
    590
   ],
   "b": [
    655,
    590
   ],
   "t": 15
  },
  {
   "a": [
    494,
    590
   ],
   "b": [
    494,
    804
   ],
   "t": 18
  },
  {
   "a": [
    147,
    804
   ],
   "b": [
    494,
    804
   ],
   "t": 15,
   "o": [
    {
     "k": "win",
     "s": 16,
     "e": 280
    }
   ]
  }
 ],
 "fixtures": [
  {
   "h": 55,
   "color": "#f4f4f2",
   "label": "Bath",
   "round": 1,
   "r": [
    570,
    14,
    70,
    135
   ]
  },
  {
   "h": 40,
   "color": "#f7f7f5",
   "label": "WC",
   "round": 1,
   "r": [
    511,
    14,
    51,
    67
   ]
  },
  {
   "h": 85,
   "label": "Basin",
   "kind": "sink",
   "r": [
    385,
    90,
    51,
    62
   ]
  },
  {
   "h": 90,
   "label": "Hob",
   "kind": "hob",
   "r": [
    104,
    253,
    48,
    129
   ]
  },
  {
   "h": 90,
   "label": "Sink",
   "kind": "sink",
   "r": [
    152,
    253,
    225,
    40
   ]
  },
  {
   "h": 50,
   "color": "#ece6da",
   "label": "bay window",
   "r": [
    163,
    806,
    264,
    53
   ]
  }
 ]
};
