// Ying Wa Court, Flat A (2 bedrooms, 466 sq ft saleable).
// Generated by tools/trace_plans.py from floorplan.jpg. Units are cm.
window.PLANS = window.PLANS || {};
window.PLANS["ying-wa-court"] = {
 "source": "Traced from the building's floor plan (2/F to 30/F) using its printed dimensions. Flats A and B are mirror images and the listing doesn't say which this is, so A is shown. Sizes are approximate (about ±15 cm).",
 "ceiling": 260,
 "defaultPreset": "office",
 "presetNames": {
  "office": "Bedroom + home office",
  "two": "Bedroom + guest bed",
  "empty": "Empty flat"
 },
 "presets": {
  "office": [
   [
    "bed-queen",
    533,
    784,
    152,
    190,
    90
   ],
   [
    "nightstand",
    610,
    684,
    35,
    40,
    90
   ],
   [
    "sofa3",
    121,
    784,
    210,
    90,
    270
   ],
   [
    "coffee",
    209,
    784,
    100,
    55,
    90
   ],
   [
    "tv",
    323,
    784,
    140,
    35,
    90
   ],
   [
    "dining4",
    172,
    485,
    120,
    75,
    90
   ],
   [
    "chair",
    125,
    438,
    45,
    50,
    270
   ],
   [
    "chair",
    125,
    532,
    45,
    50,
    270
   ],
   [
    "chair",
    218,
    438,
    45,
    50,
    90
   ],
   [
    "chair",
    218,
    532,
    45,
    50,
    90
   ],
   [
    "shoe",
    25,
    392,
    80,
    30,
    270
   ],
   [
    "desk",
    602,
    485,
    120,
    60,
    90
   ],
   [
    "officechair",
    538,
    485,
    60,
    60,
    270
   ],
   [
    "bookshelf",
    489,
    616,
    80,
    30,
    180
   ],
   [
    "wardrobe",
    382,
    849,
    100,
    55,
    90
   ]
  ],
  "two": [
   [
    "bed-queen",
    533,
    784,
    152,
    190,
    90
   ],
   [
    "nightstand",
    610,
    684,
    35,
    40,
    90
   ],
   [
    "sofa3",
    121,
    784,
    210,
    90,
    270
   ],
   [
    "coffee",
    209,
    784,
    100,
    55,
    90
   ],
   [
    "tv",
    323,
    784,
    140,
    35,
    90
   ],
   [
    "dining4",
    172,
    485,
    120,
    75,
    90
   ],
   [
    "chair",
    125,
    438,
    45,
    50,
    270
   ],
   [
    "chair",
    125,
    532,
    45,
    50,
    270
   ],
   [
    "chair",
    218,
    438,
    45,
    50,
    90
   ],
   [
    "chair",
    218,
    532,
    45,
    50,
    90
   ],
   [
    "shoe",
    25,
    392,
    80,
    30,
    270
   ],
   [
    "bed-double",
    535,
    513,
    135,
    190,
    90
   ],
   [
    "wardrobe",
    461,
    336,
    100,
    55,
    180
   ]
  ],
  "empty": []
 },
 "rooms": [
  {
   "n": "Bedroom 1",
   "x": 517,
   "y": 485,
   "dim": "2.4 × 3.1 m"
  },
  {
   "n": "Bedroom 2",
   "x": 493,
   "y": 802,
   "dim": "2.9 × 2.9 m"
  },
  {
   "n": "Living",
   "x": 209,
   "y": 802,
   "dim": "2.8 × 2.9 m"
  },
  {
   "n": "Dining",
   "x": 153,
   "y": 448
  },
  {
   "n": "Kitchen",
   "x": 106,
   "y": 187
  },
  {
   "n": "Bath",
   "x": 302,
   "y": 500
  }
 ],
 "notes": [
  {
   "x": -44,
   "y": 578,
   "text": "front door",
   "rot": -90
  }
 ],
 "reference": {
  "x": -1115.7,
  "y": -485.1,
  "w": 1847.0,
  "h": 1639.9
 },
 "bounds": [
  -24,
  -19,
  657,
  993
 ],
 "floors": [
  {
   "r": [
    0,
    321,
    638,
    313
   ],
   "kind": "wood"
  },
  {
   "r": [
    69,
    634,
    569,
    295
   ],
   "kind": "wood"
  },
  {
   "r": [
    0,
    0,
    162,
    321
   ],
   "kind": "kitchen"
  },
  {
   "r": [
    256,
    321,
    140,
    211
   ],
   "kind": "bath"
  }
 ],
 "walls": [
  {
   "a": [
    0,
    0
   ],
   "b": [
    162,
    0
   ],
   "t": 12
  },
  {
   "a": [
    162,
    0
   ],
   "b": [
    162,
    321
   ],
   "t": 12,
   "o": [
    {
     "k": "win",
     "s": 75,
     "e": 261
    }
   ]
  },
  {
   "a": [
    0,
    0
   ],
   "b": [
    0,
    634
   ],
   "t": 22,
   "o": [
    {
     "k": "door",
     "side": 1,
     "h": "e",
     "s": 532,
     "e": 629
    }
   ]
  },
  {
   "a": [
    0,
    634
   ],
   "b": [
    69,
    634
   ],
   "t": 22
  },
  {
   "a": [
    69,
    634
   ],
   "b": [
    69,
    929
   ],
   "t": 22
  },
  {
   "a": [
    162,
    321
   ],
   "b": [
    638,
    321
   ],
   "t": 16,
   "o": [
    {
     "k": "win",
     "frost": 1,
     "s": 106,
     "e": 215
    },
    {
     "k": "win",
     "s": 248,
     "e": 405
    }
   ]
  },
  {
   "a": [
    638,
    321
   ],
   "b": [
    638,
    929
   ],
   "t": 20
  },
  {
   "a": [
    69,
    929
   ],
   "b": [
    638,
    929
   ],
   "t": 16,
   "o": [
    {
     "k": "win",
     "s": 13,
     "e": 267
    },
    {
     "k": "win",
     "s": 341,
     "e": 498
    }
   ]
  },
  {
   "a": [
    256,
    321
   ],
   "b": [
    256,
    532
   ],
   "t": 10
  },
  {
   "a": [
    256,
    532
   ],
   "b": [
    396,
    532
   ],
   "t": 10,
   "o": [
    {
     "k": "door",
     "side": -1,
     "h": "s",
     "s": 13,
     "e": 69
    }
   ]
  },
  {
   "a": [
    396,
    321
   ],
   "b": [
    396,
    634
   ],
   "t": 10,
   "o": [
    {
     "k": "door",
     "side": -1,
     "h": "e",
     "s": 220,
     "e": 308
    }
   ]
  },
  {
   "a": [
    349,
    634
   ],
   "b": [
    638,
    634
   ],
   "t": 10,
   "o": [
    {
     "k": "door",
     "side": 1,
     "h": "s",
     "s": 6,
     "e": 84
    }
   ]
  },
  {
   "a": [
    349,
    634
   ],
   "b": [
    349,
    929
   ],
   "t": 10
  }
 ],
 "fixtures": [
  {
   "h": 90,
   "label": "Hob",
   "kind": "hob",
   "r": [
    6,
    47,
    50,
    267
   ]
  },
  {
   "h": 90,
   "label": "Sink",
   "kind": "sink",
   "r": [
    56,
    7,
    101,
    45
   ]
  },
  {
   "h": 55,
   "color": "#f4f4f2",
   "label": "Bath",
   "round": 1,
   "r": [
    263,
    328,
    127,
    41
   ]
  },
  {
   "h": 40,
   "color": "#f7f7f5",
   "label": "WC",
   "round": 1,
   "r": [
    306,
    392,
    45,
    62
   ]
  },
  {
   "h": 85,
   "label": "Basin",
   "kind": "sink",
   "r": [
    347,
    457,
    43,
    56
   ]
  },
  {
   "h": 50,
   "color": "#ece6da",
   "label": "bay",
   "r": [
    405,
    271,
    168,
    50
   ]
  },
  {
   "h": 50,
   "color": "#ece6da",
   "label": "bay window",
   "r": [
    78,
    929,
    261,
    50
   ]
  },
  {
   "h": 50,
   "color": "#ece6da",
   "label": "bay",
   "r": [
    405,
    929,
    168,
    50
   ]
  }
 ]
};
