"""Generates apartments/<id>/plan.js for plans traced in floor plan image pixels.

Each plan is described in the pixel coordinates of its floorplan.jpg (as
measured off the image), then converted to cm with the plan's scale.
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def build(spec):
    s, (ox, oy) = spec["px_per_cm"], spec["origin"]
    X = lambda px: round((px - ox) / s)
    Y = lambda py: round((py - oy) / s)
    P = lambda p: [X(p[0]), Y(p[1])]
    R = lambda r: [X(r[0]), Y(r[1]), round((r[2] - r[0]) / s), round((r[3] - r[1]) / s)]
    out = {k: spec[k] for k in ("source", "ceiling", "defaultPreset", "presetNames", "presets", "rooms", "notes", "marks") if k in spec}
    W, H = spec["image"]
    out["reference"] = {"x": round(-ox / s, 1), "y": round(-oy / s, 1), "w": round(W / s, 1), "h": round(H / s, 1)}
    out["bounds"] = [X(b) if i % 2 == 0 else Y(b) for i, b in enumerate(spec["bounds"])]
    out["floors"] = [{"r": R(f[0]), "kind": f[1]} for f in spec["floors"]]
    walls = []
    for w in spec["walls"]:
        a, b = P(w["a"]), P(w["b"])
        o = []
        for op in w.get("o", []):
            # openings given as pixel positions along the wall's axis
            axis = 0 if w["a"][1] == w["b"][1] else 1
            start = w["a"][axis]
            s0, e0 = sorted([abs(op["s"] - start) / s, abs(op["e"] - start) / s])
            o.append({**{k: v for k, v in op.items() if k not in ("s", "e")}, "s": round(s0), "e": round(e0)})
        walls.append({"a": a, "b": b, "t": w.get("t", 12), **({"o": o} if o else {})})
    out["walls"] = walls
    out["fixtures"] = [{**{k: v for k, v in f.items() if k != "r"}, "r": R(f["r"])} for f in spec["fixtures"]]
    return out


def write(apt_id, spec, header):
    plan = build(spec)
    path = os.path.join(ROOT, "apartments", apt_id, "plan.js")
    body = json.dumps(plan, indent=1, ensure_ascii=False)
    open(path, "w", encoding="utf8").write(
        f"// {header}\n// Generated by tools/trace_plans.py from floorplan.jpg. Units are cm.\n"
        f"window.PLANS = window.PLANS || {{}};\nwindow.PLANS[{json.dumps(apt_id)}] = {body};\n")
    print("wrote", path)


# ---------------- Beaudry Tower, Flat A (2/F-29/F), 498 sq ft saleable -----------------
# Unit plan has no printed dimensions; scale is set so the traced rooms add up to the
# saleable area and the flat's width matches the 19.75 m building width on the floor plan.
# Pixel coordinates below are in the 2045 x 2845 source image.
k = 2045 / 1438  # measured on a 1438 px wide copy
q = lambda *v: [round(x * k) for x in v]
BEAUDRY = {
    "image": [2045, 2845],
    "px_per_cm": 1.78 * k,
    "origin": q(130, 140),
    "source": "Traced from the developer's plan for Flat A (2/F to 29/F, 498 sq ft saleable), scaled to the listed area. "
              "The listing doesn't say which flat; A is the only 498 sq ft unit. Sizes are approximate (about ±15 cm).",
    "ceiling": 260,
    "bounds": q(100, 100, 1330, 1700),
    "floors": [
        [q(130, 140, 800, 575), "wood"],
        [q(390, 420, 1295, 1190), "wood"],
        [q(800, 420, 1295, 580), "wood"],
        [q(390, 1190, 1010, 1570), "wood"],
        [q(800, 140, 1295, 420), "bath"],
        [q(300, 575, 805, 825), "kitchen"],
    ],
    "walls": [
        {"a": q(130, 140), "b": q(1295, 140), "t": 15, "o": [{"s": q(410)[0], "e": q(520)[0], "k": "win"}, {"s": q(1000)[0], "e": q(1110)[0], "k": "win", "frost": 1}]},
        {"a": q(130, 140), "b": q(130, 575), "t": 20},
        {"a": q(130, 575), "b": q(805, 575), "t": 12, "o": [{"s": q(165)[0], "e": q(295)[0], "k": "win"}]},
        {"a": q(800, 140), "b": q(800, 420), "t": 12},
        {"a": q(800, 420), "b": q(1295, 420), "t": 12, "o": [{"s": q(925)[0], "e": q(1020)[0], "k": "door", "side": 1, "h": "s"}]},
        {"a": q(300, 575), "b": q(300, 825), "t": 12, "o": [{"s": q(600)[0], "e": q(800)[0], "k": "win"}]},
        {"a": q(300, 825), "b": q(805, 825), "t": 15},
        {"a": q(805, 575), "b": q(805, 825), "t": 12, "o": [{"s": q(592)[0], "e": q(718)[0], "k": "open"}]},
        {"a": q(392, 825), "b": q(392, 1570), "t": 15, "o": [{"s": q(900)[0], "e": q(1160)[0], "k": "win"}]},
        {"a": q(1295, 140), "b": q(1295, 1190), "t": 18, "o": [{"s": q(700)[0], "e": q(850)[0], "k": "door", "side": 1, "h": "e"}]},
        {"a": q(1010, 1190), "b": q(1295, 1190), "t": 15},
        {"a": q(1010, 1190), "b": q(1010, 1570), "t": 18},
        {"a": q(392, 1570), "b": q(1010, 1570), "t": 15, "o": [{"s": q(420)[0], "e": q(890)[0], "k": "win"}]},
    ],
    "fixtures": [
        {"r": q(1145, 165, 1270, 405), "h": 55, "color": "#f4f4f2", "label": "Bath", "round": 1},
        {"r": q(1040, 165, 1130, 285), "h": 40, "color": "#f7f7f5", "label": "WC", "round": 1},
        {"r": q(815, 300, 905, 410), "h": 85, "label": "Basin", "kind": "sink"},
        {"r": q(315, 590, 400, 820), "h": 90, "label": "Hob", "kind": "hob"},
        {"r": q(400, 590, 800, 660), "h": 90, "label": "Sink", "kind": "sink"},
        {"r": q(420, 1575, 890, 1670), "h": 50, "color": "#ece6da", "label": "bay window"},
    ],
    "rooms": [], "notes": [],
}
def cm(px, py):
    s, (ox, oy) = BEAUDRY["px_per_cm"], BEAUDRY["origin"]
    return round((px * k - ox) / s), round((py * k - oy) / s)

BEAUDRY["rooms"] = [
    {"n": "Bedroom", "x": cm(470, 330)[0], "y": cm(470, 330)[1], "dim": "3.8 × 2.4 m"},
    {"n": "Bath", "x": cm(960, 330)[0], "y": cm(960, 330)[1]},
    {"n": "Kitchen", "x": cm(600, 760)[0], "y": cm(600, 760)[1]},
    {"n": "Living / dining", "x": cm(840, 1000)[0], "y": cm(840, 1000)[1], "dim": "5.1 × 2.8 m + 3.5 × 2.1 m"},
]
BEAUDRY["notes"] = [{"x": cm(1330, 775)[0] + 18, "y": cm(1330, 775)[1], "text": "front door", "rot": 90},
                    {"x": cm(655, 1700)[0], "y": cm(655, 1700)[1], "text": "facing Bonham Road (sea view)"}]
c = lambda px, py: list(cm(px, py))
BEAUDRY["defaultPreset"] = "lounge"
BEAUDRY["presetNames"] = {"lounge": "Lounge + dining table", "study": "Lounge + work desk", "empty": "Empty flat"}
bed = [["bed-queen", c(130, 0)[0] + 103, 125, 152, 190, 270]]
base = [
    *bed,
    ["nightstand", 25, 22, 35, 40, 270], ["nightstand", 25, 225, 35, 40, 270],
    ["wardrobe", *c(650, 190), 120, 60],
    ["rug", *c(840, 960), 200, 140, 90],
    ["sofa3", *c(1240, 960), 210, 90, 90],
    ["coffee", *c(1100, 960), 100, 55, 90],
    ["tv", *c(430, 960), 160, 40, 270],
    ["shoe", *c(1255, 620), 80, 30, 90],
]
BEAUDRY["presets"] = {
    "lounge": base + [["dining4", *c(700, 1380), 120, 75], ["chair", *c(650, 1300), 45, 50], ["chair", *c(750, 1300), 45, 50],
                      ["chair", *c(650, 1460), 45, 50, 180], ["chair", *c(750, 1460), 45, 50, 180], ["plant", *c(950, 1520), 40, 40]],
    "study": base + [["desk", *c(700, 1500), 120, 60, 180], ["officechair", *c(700, 1420), 60, 60], ["round", *c(560, 1300), 90, 90],
                     ["bookshelf", *c(985, 1350), 80, 30, 90]],
    "empty": [],
}

# ---------------- Honor Villa, Flat A (5/F-29/F), 446 sq ft saleable -----------------
# Unit plan prints dimensions in mm (2512.5 / 2125 / 3237.5 across, 3012.5 / 2562.5 down),
# which set the scale: 0.0820 px per mm on the 1041 px wide image.
s = 0.820
HONOR = {
    "image": [1041, 955],
    "px_per_cm": s,
    "origin": [243, 88],
    "source": "Traced from the developer's plan for Flat A (5/F to 29/F, 446 sq ft saleable) using its printed dimensions. "
              "The listing doesn't say which flat; A is the only 446 sq ft unit. The front door position is inferred.",
    "ceiling": 265,
    "bounds": [235, 80, 900, 600],
    "floors": [
        [[272, 100, 400, 333], "bath"],
        [[400, 100, 598, 255], "kitchen"],
        [[400, 255, 840, 333], "wood"],
        [[598, 100, 840, 333], "wood"],
        [[272, 333, 885, 548], "wood"],
    ],
    "walls": [
        {"a": [258, 94], "b": [855, 94], "t": 14, "o": [{"s": 770, "e": 830, "k": "door", "side": 1, "h": "e"}]},
        {"a": [258, 94], "b": [258, 548], "t": 24},
        {"a": [855, 94], "b": [855, 360], "t": 26},
        {"a": [855, 360], "b": [882, 360], "t": 12},
        {"a": [882, 360], "b": [882, 548], "t": 14, "o": [{"s": 415, "e": 545, "k": "win"}]},
        {"a": [258, 548], "b": [882, 548], "t": 12, "o": [{"s": 315, "e": 445, "k": "win"}, {"s": 490, "e": 620, "k": "win"}, {"s": 662, "e": 880, "k": "win"}]},
        {"a": [400, 94], "b": [400, 333], "t": 10, "o": [{"s": 268, "e": 326, "k": "door", "side": -1, "h": "e"}]},
        {"a": [400, 255], "b": [598, 255], "t": 10},
        {"a": [598, 94], "b": [598, 145], "t": 10},
        {"a": [258, 333], "b": [448, 333], "t": 10, "o": [{"s": 372, "e": 440, "k": "door", "side": 1, "h": "e"}]},
        {"a": [448, 333], "b": [448, 548], "t": 10},
        {"a": [448, 333], "b": [625, 333], "t": 10, "o": [{"s": 452, "e": 520, "k": "door", "side": 1, "h": "s"}]},
        {"a": [625, 333], "b": [625, 548], "t": 10},
    ],
    "fixtures": [
        {"r": [282, 108, 392, 152], "h": 55, "color": "#f4f4f2", "label": "Bath", "round": 1},
        {"r": [340, 180, 380, 228], "h": 40, "color": "#f7f7f5", "label": "WC", "round": 1},
        {"r": [276, 232, 312, 282], "h": 85, "label": "Basin", "kind": "sink"},
        {"r": [406, 104, 448, 250], "h": 90, "label": "Hob", "kind": "hob"},
        {"r": [448, 104, 594, 140], "h": 90, "label": "Sink", "kind": "sink"},
        {"r": [312, 548, 448, 585], "h": 50, "color": "#ece6da", "label": "bay"},
        {"r": [488, 548, 622, 585], "h": 50, "color": "#ece6da", "label": "bay"},
        {"r": [660, 548, 885, 585], "h": 50, "color": "#ece6da", "label": "bay window"},
    ],
}
cH = lambda px, py: [round((px - 243) / s), round((py - 88) / s)]
HONOR["rooms"] = [
    {"n": "Bedroom 1", "x": cH(360, 470)[0], "y": cH(360, 470)[1], "dim": "2.3 × 2.6 m"},
    {"n": "Bedroom 2", "x": cH(537, 470)[0], "y": cH(537, 470)[1], "dim": "2.0 × 2.6 m"},
    {"n": "Living", "x": cH(755, 470)[0], "y": cH(755, 470)[1], "dim": "3.1 × 2.6 m"},
    {"n": "Dining", "x": cH(720, 200)[0], "y": cH(720, 200)[1], "dim": "2.9 × 2.9 m"},
    {"n": "Kitchen", "x": cH(520, 200)[0], "y": cH(520, 200)[1]},
    {"n": "Bath", "x": cH(335, 300)[0], "y": cH(335, 300)[1]},
]
HONOR["notes"] = [{"x": cH(800, 80)[0], "y": cH(800, 80)[1] - 4, "text": "front door (approx.)"},
                  {"x": cH(570, 600)[0], "y": cH(570, 600)[1] + 8, "text": "facing Caine Road"}]
HONOR["defaultPreset"] = "two"
HONOR["presetNames"] = {"two": "Double bed + guest/study", "office": "Double bed + home office", "empty": "Empty flat"}
hb = [
    ["bed-double", cH(272, 0)[0] + 101, cH(0, 455)[1], 135, 190, 270],
    ["nightstand", cH(272, 0)[0] + 20, cH(0, 355)[1], 35, 40, 270],
    ["sofa3", cH(670, 0)[0], cH(0, 440)[1], 210, 90, 270],
    ["coffee", cH(760, 0)[0], cH(0, 440)[1], 100, 55, 90],
    ["tv", cH(860, 0)[0], cH(0, 440)[1], 160, 40, 90],
    ["dining4", *cH(725, 205), 120, 75], ["chair", *cH(700, 160), 45, 50], ["chair", *cH(750, 160), 45, 50],
    ["chair", *cH(700, 250), 45, 50, 180], ["chair", *cH(750, 250), 45, 50, 180],
    ["shoe", *cH(830, 150), 80, 30, 270],
]
HONOR["presets"] = {
    "two": hb + [["bed-single", *cH(585, 455), 90, 190, 180], ["dresser", *cH(500, 525), 80, 40, 180]],
    "office": hb + [["desk", *cH(537, 515), 120, 60, 180], ["officechair", *cH(537, 465), 60, 60], ["bookshelf", *cH(612, 420), 80, 30, 270]],
    "empty": [],
}

if __name__ == "__main__":
    write("beaudry-tower", BEAUDRY, "Beaudry Tower, Flat A (1 bedroom, 498 sq ft saleable).")
    write("honor-villa", HONOR, "Honor Villa, Flat A (2 bedrooms, 446 sq ft saleable).")
